export const majorCities = [
    // Southern California (20)
    "Los Angeles, USA",
    "San Diego, USA",
    "Anaheim, USA",
    "Santa Ana, USA",
    "Riverside, USA",
    "Irvine, USA",
    "Long Beach, USA",
    "San Bernardino, USA",
    "Chula Vista, USA",
    "Glendale, USA",
    "Santa Clarita, USA",
    "Huntington Beach, USA",
    "Garden Grove, USA",
    "Ontario, USA",
    "Pomona, USA",
    "Palmdale, USA",
    "Pasadena, USA",
    "Torrance, USA",
    "Orange, USA",
    "Fullerton, USA",

    // North America (Major)
    "New York, USA",
    "Chicago, USA",
    "Houston, USA",
    "Phoenix, USA",
    "Philadelphia, USA",
    "San Antonio, USA",
    "Dallas, USA",
    "San Jose, USA",
    "San Francisco, USA",
    "Austin, USA",
    "Seattle, USA",
    "Denver, USA",
    "Miami, USA",
    "Boston, USA",
    "Toronto, Canada",
    "Montreal, Canada",
    "Vancouver, Canada",
    "Mexico City, Mexico",
    "Guadalajara, Mexico",
    "Monterrey, Mexico",

    // Europe
    "London, UK",
    "Birmingham, UK",
    "Manchester, UK",
    "Paris, France",
    "Marseille, France",
    "Lyon, France",
    "Berlin, Germany",
    "Hamburg, Germany",
    "Munich, Germany",
    "Frankfurt, Germany",
    "Madrid, Spain",
    "Barcelona, Spain",
    "Valencia, Spain",
    "Rome, Italy",
    "Milan, Italy",
    "Naples, Italy",
    "Vienna, Austria",
    "Amsterdam, Netherlands",
    "Brussels, Belgium",
    "Lisbon, Portugal",
    "Zurich, Switzerland",
    "Geneva, Switzerland",
    "Dublin, Ireland",
    "Copenhagen, Denmark",
    "Stockholm, Sweden",
    "Oslo, Norway",
    "Helsinki, Finland",
    "Warsaw, Poland",
    "Prague, Czech Republic",
    "Budapest, Hungary",
    "Athens, Greece",
    "Istanbul, Turkey",
    "Moscow, Russia",
    "Saint Petersburg, Russia",
    "Kiev, Ukraine",
    "Bucharest, Romania",

    // Asia
    "Tokyo, Japan",
    "Osaka, Japan",
    "Yokohama, Japan",
    "Seoul, South Korea",
    "Busan, South Korea",
    "Beijing, China",
    "Shanghai, China",
    "Guangzhou, China",
    "Shenzhen, China",
    "Chengdu, China",
    "Hong Kong, China",
    "Taipei, Taiwan",
    "Mumbai, India",
    "Delhi, India",
    "Bangalore, India",
    "Hyderabad, India",
    "Chennai, India",
    "Kolkata, India",
    "Karachi, Pakistan",
    "Lahore, Pakistan",
    "Islamabad, Pakistan",
    "Dhaka, Bangladesh",
    "Jakarta, Indonesia",
    "Surabaya, Indonesia",
    "Manila, Philippines",
    "Bangkok, Thailand",
    "Ho Chi Minh City, Vietnam",
    "Hanoi, Vietnam",
    "Kuala Lumpur, Malaysia",
    "Singapore, Singapore",
    "Tehran, Iran",
    "Baghdad, Iraq",
    "Riyadh, Saudi Arabia",
    "Jeddah, Saudi Arabia",
    "Mecca, Saudi Arabia",
    "Medina, Saudi Arabia",
    "Dubai, UAE",
    "Abu Dhabi, UAE",
    "Doha, Qatar",
    "Kuwait City, Kuwait",
    "Manama, Bahrain",
    "Muscat, Oman",
    "Beirut, Lebanon",
    "Amman, Jordan",
    "Tel Aviv, Israel",
    "Jerusalem, Israel",

    // Africa
    "Cairo, Egypt",
    "Alexandria, Egypt",
    "Lagos, Nigeria",
    "Kano, Nigeria",
    "Kinshasa, DRC",
    "Johannesburg, South Africa",
    "Cape Town, South Africa",
    "Durban, South Africa",
    "Nairobi, Kenya",
    "Addis Ababa, Ethiopia",
    "Casablanca, Morocco",
    "Algiers, Algeria",
    "Tunis, Tunisia",
    "Khartoum, Sudan",
    "Dar es Salaam, Tanzania",
    "Accra, Ghana",

    // South America
    "São Paulo, Brazil",
    "Rio de Janeiro, Brazil",
    "Buenos Aires, Argentina",
    "Santiago, Chile",
    "Bogotá, Colombia",
    "Lima, Peru",
    "Caracas, Venezuela",
    "Quito, Ecuador",
    "Montevideo, Uruguay",

    // Oceania
    "Sydney, Australia",
    "Melbourne, Australia",
    "Brisbane, Australia",
    "Perth, Australia",
    "Auckland, New Zealand"
].sort();
