export const ethnicities = [
    "Achenes",
    "Afar",
    "Afghan",
    "African American",
    "Albanian",
    "Algerian",
    "Amazigh",
    "Arab",
    "Azeri",
    "Balinese",
    "Baloch",
    "Bambara",
    "Bangladeshi",
    "Bosniak",
    "Caribbean",
    "Central African",
    "Central Asian",
    "Chadian",
    "Chechen",
    "Chinese",
    "Circassian",
    "East African",
    "East Asian",
    "Egyptian",
    "Eritrean",
    "Ethiopian",
    "European",
    "Fulani",
    "Ghanian",
    "Guinean",
    "Gujrati",
    "Hausa",
    "Hazara",
    "Hispanic",
    "Hui",
    "Indian",
    "Indonesian",
    "Iraqi",
    "Kashmiri",
    "Kazakh",
    "Kenyan",
    "Khaleeji",
    "Kurd",
    "Latino",
    "Lebanese",
    "Levant",
    "Libyan",
    "Madurese",
    "Maghreb",
    "Malay",
    "Mande",
    "Moro",
    "Moroccan",
    "Nigerian",
    "North African",
    "Oromo",
    "Other",
    "Pakistani",
    "Palestinian",
    "Pashtun",
    "Persian",
    "Punjabi",
    "Saudi",
    "Somali",
    "Sudanese",
    "Swahili",
    "Syrian",
    "Tajic",
    "Tunisian",
    "Turkish",
    "Uyghur",
    "West African",
    "Wolof",
    "Yemeni",
    "Yoruba"
].sort();
